from __future__ import annotations

from dataclasses import dataclass
from typing import Iterable

from .effective_access import MqttEffectiveAccessCompiler, MqttEffectiveAccessEntry
from .integration_models import MqttIntegrationState
from .topic_families import BOOTSTRAP_TOPIC


DEFAULT_RESERVED_PREFIXES: tuple[str, ...] = (
    "synthia/system/#",
    "synthia/core/#",
    "synthia/supervisor/#",
    "synthia/scheduler/#",
    "synthia/policy/#",
    "synthia/telemetry/#",
)
DEFAULT_BOOTSTRAP_TOPIC = BOOTSTRAP_TOPIC


@dataclass(frozen=True)
class CompiledAclRule:
    principal_id: str
    action: str
    topic: str
    effect: str


@dataclass(frozen=True)
class MqttAclCompilationResult:
    rules: list[CompiledAclRule]
    acl_text: str
    effective_access: list[MqttEffectiveAccessEntry]


def _sorted_unique(items: Iterable[str]) -> list[str]:
    return sorted({str(item).strip() for item in items if str(item).strip()})


class MqttAclCompiler:
    def __init__(
        self,
        *,
        bootstrap_topic: str = DEFAULT_BOOTSTRAP_TOPIC,
        reserved_prefixes: Iterable[str] | None = None,
    ) -> None:
        self._bootstrap_topic = str(bootstrap_topic or DEFAULT_BOOTSTRAP_TOPIC).strip() or DEFAULT_BOOTSTRAP_TOPIC
        self._reserved = _sorted_unique(reserved_prefixes or DEFAULT_RESERVED_PREFIXES)
        self._effective_access = MqttEffectiveAccessCompiler(
            bootstrap_topic=self._bootstrap_topic,
            reserved_prefixes=list(self._reserved),
        )

    def compile(self, state: MqttIntegrationState) -> MqttAclCompilationResult:
        entries = self._effective_access.compile(state)
        rules = self._render_mosquitto_rules(entries)
        normalized = sorted(set(rules), key=lambda item: (item.principal_id, item.action, item.topic, item.effect))
        return MqttAclCompilationResult(rules=normalized, acl_text=self._to_acl_text(normalized), effective_access=entries)

    def compile_effective_access(self, state: MqttIntegrationState) -> list[MqttEffectiveAccessEntry]:
        return self._effective_access.compile(state)

    def inspect_effective_access(self, state: MqttIntegrationState, principal_id: str) -> MqttEffectiveAccessEntry | None:
        return self._effective_access.inspect_principal(state, principal_id)

    @staticmethod
    def _render_mosquitto_rules(entries: list[MqttEffectiveAccessEntry]) -> list[CompiledAclRule]:
        rules: list[CompiledAclRule] = []
        for entry in entries:
            if entry.principal_id == "anonymous":
                for topic in entry.subscribe_scopes:
                    rules.append(CompiledAclRule("anonymous", "subscribe", topic, "allow"))
                rules.append(CompiledAclRule("anonymous", "publish", "#", "deny"))
                rules.append(CompiledAclRule("anonymous", "subscribe", "#", "deny"))
                continue
            for topic in entry.publish_scopes:
                rules.append(CompiledAclRule(entry.principal_id, "publish", topic, "allow"))
            for topic in entry.subscribe_scopes:
                rules.append(CompiledAclRule(entry.principal_id, "subscribe", topic, "allow"))
            if entry.principal_type == "generic_user":
                for prefix in entry.reserved_prefix_denies:
                    rules.append(CompiledAclRule("generic_user:*", "publish", prefix, "deny"))
                    rules.append(CompiledAclRule("generic_user:*", "subscribe", prefix, "deny"))
        return rules

    def _to_acl_text(self, rules: list[CompiledAclRule]) -> str:
        lines: list[str] = []
        lines.append("# generated by synthia core mqtt acl compiler")
        for rule in rules:
            lines.append(f"{rule.principal_id} {rule.effect} {rule.action} {rule.topic}")
        return "\n".join(lines) + "\n"
